### ISSUE TITLE
Widget error on refresh

### ISSUE THREAD

**Issue by evilC** [CapnBry/ElrsTelemWidget#3]
When I try to add the widget, I get the following error:
```
refresh(): /WIDGETS/ELRST/main.lua:179: attempt to perform arithmetic on local 'rangeCLR' (a nil value)
```
RadioMaster TX16s running OpenTX2.3.14, and HappyModel ES24 TX running ELRS 2.2.0

TBH I don't really think that this widget is what I want, what I really want is a widget that tells me if my radio can see my ELRS module.
It can be a bit iffy on startup of the radio, and at the moment I have to go into the SYS menu, run the ELRS LUA script, and if the information populates (ie I see packet rate etc), then I know the radio can see the ELRS module
So ideally all I want is something on my home screen that tells me if it can see the module (eg showing the packet rate that the module is set to would suffice) to save me having to go into the SYS menu each time
Do you know if this is possible?

**Comment by CapnBry** [comment]
This widget does not work on OpenTX 2.3.14, it requires EdgeTX 2.4 or above.

It also can not tell you if a module is attached, because neither handset firmware can do this without a receiver connected. If a receiver is connected you know there is an ELRS module because it connected though. I'm not sure why you need to know if the module is "seen" by the handset firmware. If you look at the module and the lights are on, it is on and should be connected to the handset (assuming the protocol is set to CRSF and not like MULTI).

There are plans to eventually have a widget implementation of the ELRSv2.lua (which will do what you're asking), but that's several months away and will require EdgeTX as well.

**Comment by evilC** [comment]
> It also can not tell you if a module is attached, because neither handset firmware can do this without a receiver connected

If you run the ELRS lua script without the module properly plugged in, you don't get data (ie it does not populate Packet Rate etc values)

>  If  you look at the module and the lights are on, it is on and should be connected to the handset

Not always the case I am afraid. Happens to me all the time, I need to power the radio off, jiggle the module bay around a little / press it in a little, restart the radio and it springs into life.  
Oddly, it never cuts out once the radio has started up and connected to the module, it only ever happens at boot time.  
I was just hoping that I could get something that showed on my home screen that everything is good, without having to delve into the SYS menu to run the script

**Comment by CapnBry** [comment]
The ELRS script can see the radio because it is actively sending data to the TX. This widget is completely passive, it just displays the telemetry the TX already sends. Unfortunately no data is passively available if there is no RX connected.

**Comment by evilC** [comment]
OK, thanks for the clarification
